
return {
    ["u"] = {text = "是", weight = 4},
    ["s"] = {text = "所", weight = 1},
    ["q"] = {text = "去", weight = 1},
    ["w"] = {text = "我", weight = 2},
    ["y"] = {text = "有", weight = 2},
    ["o"] = {text = "哦", weight = 1},
    ["d"] = {text = "的", weight = 3},
    ["g"] = {text = "個", weight = 1},
    ["h"] = {text = "和", weight = 1},
    ["j"] = {text = "就", weight = 1},
    ["k"] = {text = "可", weight = 1},
    ["l"] = {text = "了", weight = 1},
    ["z"] = {text = "在", weight = 2},
    ["x"] = {text = "下", weight = 1},
    ["c"] = {text = "才", weight = 1},
    ["b"] = {text = "吧", weight = 2},
    ["n"] = {text = "你", weight = 1},
    ["m"] = {text = "嗎", weight = 1},
    ["v"] = {text = "這", weight = 2},
    ["de"] = {text = "得", weight = 1},
    ["da"] = {text = "大", weight = 1},
    ["ba"] = {text = "把", weight = 1},
    ["na"] = {text = "那", weight = 1},
    ["b;"] = {text = "冰", weight = 1},
    ["ba"] = {text = "把", weight = 1},
    ["bc"] = {text = "表", weight = 1},
    ["bf"] = {text = "本", weight = 1},
    ["bg"] = {text = "崩", weight = 1},
    ["bh"] = {text = "幫", weight = 1},
    ["bi"] = {text = "比", weight = 1},
    ["bj"] = {text = "半", weight = 1},
    ["bk"] = {text = "包", weight = 1},
    ["bl"] = {text = "白", weight = 1},
    ["bm"] = {text = "變", weight = 1},
    ["bn"] = {text = "賓", weight = 1},
    ["bo"] = {text = "波", weight = 1},
    ["bu"] = {text = "不", weight = 1},
    ["bx"] = {text = "別", weight = 1},
    ["bz"] = {text = "被", weight = 1},
    ["ca"] = {text = "擦", weight = 1},
    ["cb"] = {text = "湊", weight = 1},
    ["ce"] = {text = "測", weight = 1},
    ["cf"] = {text = "岑", weight = 1},
    ["cg"] = {text = "層", weight = 1},
    ["ch"] = {text = "藏", weight = 1},
    ["ci"] = {text = "次", weight = 1},
    ["cj"] = {text = "參", weight = 1},
    ["ck"] = {text = "草", weight = 1},
    ["cl"] = {text = "才", weight = 1},
    ["co"] = {text = "錯", weight = 1},
    ["cp"] = {text = "存", weight = 1},
    ["cr"] = {text = "竄", weight = 1},
    ["cs"] = {text = "從", weight = 1},
    ["cu"] = {text = "粗", weight = 1},
    ["cv"] = {text = "催", weight = 1},
    ["d;"] = {text = "定", weight = 1},
    ["da"] = {text = "大", weight = 1},
    ["db"] = {text = "都", weight = 1},
    ["dc"] = {text = "掉", weight = 1},
    ["dg"] = {text = "等", weight = 1},
    ["dh"] = {text = "當", weight = 1},
    ["di"] = {text = "地", weight = 1},
    ["dj"] = {text = "但", weight = 1},
    ["dk"] = {text = "到", weight = 1},
    ["dl"] = {text = "帶", weight = 1},
    ["dm"] = {text = "點", weight = 1},
    ["do"] = {text = "多", weight = 1},
    ["dp"] = {text = "盾", weight = 1},
    ["dq"] = {text = "丟", weight = 1},
    ["dr"] = {text = "斷", weight = 1},
    ["ds"] = {text = "動", weight = 1},
    ["du"] = {text = "度", weight = 1},
    ["dv"] = {text = "對", weight = 1},
    ["dx"] = {text = "爹", weight = 1},
    ["dz"] = {text = "得", weight = 1},
    ["fa"] = {text = "發", weight = 1},
    ["fb"] = {text = "否", weight = 1},
    ["ff"] = {text = "分", weight = 1},
    ["fg"] = {text = "風", weight = 1},
    ["fh"] = {text = "放", weight = 1},
    ["fj"] = {text = "反", weight = 1},
    ["fo"] = {text = "佛", weight = 1},
    ["fu"] = {text = "服", weight = 1},
    ["fz"] = {text = "飛", weight = 1},
    ["ga"] = {text = "嘎", weight = 1},
    ["gb"] = {text = "狗", weight = 1},
    ["gd"] = {text = "光", weight = 1},
    ["ge"] = {text = "個", weight = 1},
    ["gf"] = {text = "跟", weight = 1},
    ["gg"] = {text = "更", weight = 1},
    ["gh"] = {text = "剛", weight = 1},
    ["gj"] = {text = "感", weight = 1},
    ["gk"] = {text = "高", weight = 1},
    ["gl"] = {text = "該", weight = 1},
    ["go"] = {text = "過", weight = 1},
    ["gp"] = {text = "滾", weight = 1},
    ["gr"] = {text = "關", weight = 1},
    ["gs"] = {text = "公", weight = 1},
    ["gu"] = {text = "古", weight = 1},
    ["gv"] = {text = "鬼", weight = 1},
    ["gw"] = {text = "掛", weight = 1},
    ["gy"] = {text = "怪", weight = 1},
    ["gz"] = {text = "給", weight = 1},
    ["ha"] = {text = "哈", weight = 1},
    ["hb"] = {text = "後", weight = 1},
    ["hd"] = {text = "黃", weight = 1},
    ["he"] = {text = "和", weight = 1},
    ["hf"] = {text = "很", weight = 1},
    ["hg"] = {text = "哼", weight = 1},
    ["hh"] = {text = "航", weight = 1},
    ["hj"] = {text = "漢", weight = 1},
    ["hk"] = {text = "好", weight = 1},
    ["hl"] = {text = "還", weight = 1},
    ["ho"] = {text = "或", weight = 1},
    ["hp"] = {text = "混", weight = 1},
    ["hr"] = {text = "換", weight = 1},
    ["hs"] = {text = "紅", weight = 1},
    ["hu"] = {text = "乎", weight = 1},
    ["hv"] = {text = "會", weight = 1},
    ["hw"] = {text = "話", weight = 1},
    ["hy"] = {text = "壞", weight = 1},
    ["hz"] = {text = "黑", weight = 1},
    ["ia"] = {text = "差", weight = 1},
    ["ib"] = {text = "抽", weight = 1},
    ["id"] = {text = "創", weight = 1},
    ["ie"] = {text = "車", weight = 1},
    ["if"] = {text = "沉", weight = 1},
    ["ig"] = {text = "成", weight = 1},
    ["ih"] = {text = "長", weight = 1},
    ["ii"] = {text = "喫", weight = 1},
    ["ij"] = {text = "產", weight = 1},
    ["ik"] = {text = "超", weight = 1},
    ["il"] = {text = "拆", weight = 1},
    ["io"] = {text = "戳", weight = 1},
    ["ip"] = {text = "純", weight = 1},
    ["ir"] = {text = "傳", weight = 1},
    ["is"] = {text = "衝", weight = 1},
    ["iu"] = {text = "出", weight = 1},
    ["iv"] = {text = "吹", weight = 1},
    ["iy"] = {text = "踹", weight = 1},
    ["j;"] = {text = "經", weight = 1},
    ["jc"] = {text = "叫", weight = 1},
    ["jd"] = {text = "將", weight = 1},
    ["ji"] = {text = "級", weight = 1},
    ["jm"] = {text = "見", weight = 1},
    ["jn"] = {text = "進", weight = 1},
    ["jp"] = {text = "君", weight = 1},
    ["jq"] = {text = "就", weight = 1},
    ["jr"] = {text = "卷", weight = 1},
    ["js"] = {text = "囧", weight = 1},
    ["jt"] = {text = "絕", weight = 1},
    ["ju"] = {text = "句", weight = 1},
    ["jw"] = {text = "家", weight = 1},
    ["jx"] = {text = "接", weight = 1},
    ["ka"] = {text = "卡", weight = 1},
    ["kb"] = {text = "口", weight = 1},
    ["kd"] = {text = "狂", weight = 1},
    ["ke"] = {text = "可", weight = 1},
    ["kf"] = {text = "肯", weight = 1},
    ["kg"] = {text = "坑", weight = 1},
    ["kh"] = {text = "抗", weight = 1},
    ["kj"] = {text = "看", weight = 1},
    ["kk"] = {text = "靠", weight = 1},
    ["kl"] = {text = "開", weight = 1},
    ["ko"] = {text = "擴", weight = 1},
    ["kp"] = {text = "坤", weight = 1},
    ["kr"] = {text = "寬", weight = 1},
    ["ks"] = {text = "空", weight = 1},
    ["ku"] = {text = "苦", weight = 1},
    ["kv"] = {text = "虧", weight = 1},
    ["kw"] = {text = "跨", weight = 1},
    ["ky"] = {text = "快", weight = 1},
    ["kz"] = {text = "剋", weight = 1},
    ["l;"] = {text = "令", weight = 1},
    ["la"] = {text = "拉", weight = 1},
    ["lb"] = {text = "樓", weight = 1},
    ["lc"] = {text = "聊", weight = 1},
    ["ld"] = {text = "量", weight = 1},
    ["le"] = {text = "樂", weight = 2},
    ["le"] = {text = "了", weight = 1},
    ["lg"] = {text = "冷", weight = 1},
    ["lh"] = {text = "狼", weight = 1},
    ["li"] = {text = "裏", weight = 1},
    ["lj"] = {text = "藍", weight = 1},
    ["lk"] = {text = "老", weight = 1},
    ["ll"] = {text = "來", weight = 1},
    ["lm"] = {text = "連", weight = 1},
    ["ln"] = {text = "林", weight = 1},
    ["lo"] = {text = "落", weight = 1},
    ["lp"] = {text = "論", weight = 1},
    ["lq"] = {text = "留", weight = 1},
    ["lr"] = {text = "亂", weight = 1},
    ["ls"] = {text = "龍", weight = 1},
    ["lt"] = {text = "略", weight = 1},
    ["lu"] = {text = "路", weight = 1},
    ["lw"] = {text = "倆", weight = 1},
    ["lx"] = {text = "列", weight = 1},
    ["ly"] = {text = "綠", weight = 1},
    ["lz"] = {text = "雷", weight = 1},
    ["m;"] = {text = "明", weight = 1},
    ["ma"] = {text = "馬", weight = 2},
    -- ["ma"] = {text = "嗎", weight = 1},
    ["mb"] = {text = "某", weight = 1},
    ["mc"] = {text = "妙", weight = 1},
    ["me"] = {text = "麼", weight = 1},
    ["mf"] = {text = "門", weight = 2},
    ["mf"] = {text = "們", weight = 1},
    ["mg"] = {text = "夢", weight = 1},
    ["mh"] = {text = "忙", weight = 1},
    ["mi"] = {text = "米", weight = 1},
    ["mj"] = {text = "滿", weight = 1},
    ["mk"] = {text = "毛", weight = 1},
    ["ml"] = {text = "買", weight = 1},
    ["mm"] = {text = "面", weight = 1},
    ["mn"] = {text = "民", weight = 1},
    ["mo"] = {text = "魔", weight = 1},
    ["mq"] = {text = "謬", weight = 1},
    ["mu"] = {text = "木", weight = 1},
    ["mx"] = {text = "滅", weight = 1},
    ["mz"] = {text = "沒", weight = 1},
    ["n;"] = {text = "寧", weight = 1},
    ["na"] = {text = "那", weight = 1},
    ["nc"] = {text = "鳥", weight = 1},
    ["nd"] = {text = "娘", weight = 1},
    ["ne"] = {text = "呢", weight = 1},
    ["nf"] = {text = "嫩", weight = 1},
    ["ng"] = {text = "能", weight = 1},
    ["nh"] = {text = "囊", weight = 1},
    ["ni"] = {text = "你", weight = 1},
    ["nj"] = {text = "難", weight = 1},
    ["nk"] = {text = "鬧", weight = 1},
    ["nl"] = {text = "奶", weight = 1},
    ["nm"] = {text = "年", weight = 1},
    ["nn"] = {text = "您", weight = 1},
    ["no"] = {text = "諾", weight = 1},
    ["nq"] = {text = "牛", weight = 1},
    ["nr"] = {text = "暖", weight = 1},
    ["ns"] = {text = "弄", weight = 1},
    ["nt"] = {text = "虐", weight = 1},
    ["nu"] = {text = "怒", weight = 1},
    ["nx"] = {text = "捏", weight = 1},
    ["ny"] = {text = "女", weight = 1},
    ["nz"] = {text = "內", weight = 1},
    ["oa"] = {text = "啊", weight = 1},
    ["ob"] = {text = "歐", weight = 1},
    ["oe"] = {text = "呃", weight = 1},
    ["of"] = {text = "嗯", weight = 1},
    ["og"] = {text = "嗯", weight = 1},
    ["oh"] = {text = "昂", weight = 1},
    ["oj"] = {text = "安", weight = 1},
    ["ok"] = {text = "奧", weight = 1},
    ["ol"] = {text = "哎", weight = 1},
    ["oo"] = {text = "哦", weight = 1},
    ["or"] = {text = "而", weight = 1},
    ["oz"] = {text = "誒", weight = 1},
    ["p;"] = {text = "平", weight = 1},
    ["pa"] = {text = "爬", weight = 1},
    ["pb"] = {text = "剖", weight = 1},
    ["pc"] = {text = "票", weight = 1},
    ["pf"] = {text = "噴", weight = 1},
    ["pg"] = {text = "朋", weight = 1},
    ["ph"] = {text = "旁", weight = 1},
    ["pi"] = {text = "皮", weight = 1},
    ["pj"] = {text = "盤", weight = 1},
    ["pk"] = {text = "跑", weight = 1},
    ["pl"] = {text = "排", weight = 1},
    ["pm"] = {text = "片", weight = 1},
    ["pn"] = {text = "品", weight = 1},
    ["po"] = {text = "破", weight = 1},
    ["pu"] = {text = "普", weight = 1},
    ["px"] = {text = "撇", weight = 1},
    ["pz"] = {text = "陪", weight = 1},
    ["q;"] = {text = "請", weight = 1},
    ["qc"] = {text = "巧", weight = 1},
    ["qd"] = {text = "強", weight = 1},
    ["qi"] = {text = "其", weight = 1},
    ["qm"] = {text = "前", weight = 1},
    ["qn"] = {text = "親", weight = 1},
    ["qp"] = {text = "羣", weight = 1},
    ["qq"] = {text = "求", weight = 1},
    ["qr"] = {text = "全", weight = 1},
    ["qs"] = {text = "窮", weight = 1},
    ["qt"] = {text = "卻", weight = 1},
    ["qu"] = {text = "去", weight = 1},
    ["qw"] = {text = "恰", weight = 1},
    ["qx"] = {text = "且", weight = 1},
    ["rb"] = {text = "肉", weight = 1},
    ["re"] = {text = "熱", weight = 1},
    ["rf"] = {text = "人", weight = 1},
    ["rg"] = {text = "仍", weight = 1},
    ["rh"] = {text = "讓", weight = 1},
    ["ri"] = {text = "日", weight = 1},
    ["rj"] = {text = "然", weight = 1},
    ["rk"] = {text = "繞", weight = 1},
    ["ro"] = {text = "若", weight = 1},
    ["rp"] = {text = "潤", weight = 1},
    ["rr"] = {text = "軟", weight = 1},
    ["rs"] = {text = "容", weight = 1},
    ["ru"] = {text = "如", weight = 2},
    ["ru"] = {text = "入", weight = 1},
    ["rv"] = {text = "瑞", weight = 1},
    ["sa"] = {text = "薩", weight = 1},
    ["sb"] = {text = "搜", weight = 1},
    ["se"] = {text = "色", weight = 1},
    ["sf"] = {text = "森", weight = 1},
    ["sg"] = {text = "僧", weight = 1},
    ["sh"] = {text = "喪", weight = 1},
    ["si"] = {text = "死", weight = 1},
    ["sj"] = {text = "三", weight = 1},
    ["sk"] = {text = "掃", weight = 1},
    ["sl"] = {text = "賽", weight = 1},
    ["so"] = {text = "所", weight = 1},
    ["sp"] = {text = "孫", weight = 1},
    ["sr"] = {text = "算", weight = 1},
    ["ss"] = {text = "送", weight = 1},
    ["su"] = {text = "訴", weight = 1},
    ["sv"] = {text = "雖", weight = 1},
    ["sz"] = {text = "塞", weight = 1},
    ["t;"] = {text = "聽", weight = 1},
    ["ta"] = {text = "他", weight = 1},
    ["tb"] = {text = "頭", weight = 1},
    ["tc"] = {text = "條", weight = 1},
    ["te"] = {text = "特", weight = 1},
    ["tg"] = {text = "疼", weight = 1},
    ["th"] = {text = "唐", weight = 1},
    ["ti"] = {text = "題", weight = 1},
    ["tj"] = {text = "談", weight = 1},
    ["tk"] = {text = "逃", weight = 1},
    ["tl"] = {text = "太", weight = 1},
    ["tm"] = {text = "天", weight = 1},
    ["to"] = {text = "拖", weight = 1},
    ["tp"] = {text = "屯", weight = 1},
    ["tr"] = {text = "團", weight = 1},
    ["ts"] = {text = "同", weight = 1},
    ["tu"] = {text = "土", weight = 1},
    ["tv"] = {text = "推", weight = 2},
    -- ["tv"] = {text = "退", weight = 1},
    ["tx"] = {text = "鐵", weight = 1},
    ["ua"] = {text = "啥", weight = 1},
    ["ub"] = {text = "手", weight = 1},
    ["ud"] = {text = "爽", weight = 1},
    ["ue"] = {text = "射", weight = 1},
    ["uf"] = {text = "神", weight = 1},
    ["ug"] = {text = "生", weight = 1},
    ["uh"] = {text = "上", weight = 1},
    ["ui"] = {text = "是", weight = 1},
    ["uj"] = {text = "山", weight = 1},
    ["uk"] = {text = "少", weight = 1},
    ["ul"] = {text = "曬", weight = 1},
    ["uo"] = {text = "說", weight = 1},
    ["up"] = {text = "順", weight = 1},
    ["ur"] = {text = "涮", weight = 1},
    -- ["uu"] = {text = "書", weight = 2},
    ["uu"] = {text = "數", weight = 1},
    -- ["uv"] = {text = "睡", weight = 3},
    ["uv"] = {text = "水", weight = 2},
    -- ["uv"] = {text = "誰", weight = 1},
    ["uw"] = {text = "刷", weight = 1},
    ["uy"] = {text = "帥", weight = 1},
    ["uz"] = {text = "誰", weight = 1},
    ["va"] = {text = "炸", weight = 1},
    ["vb"] = {text = "舟", weight = 1},
    ["vd"] = {text = "裝", weight = 1},
    ["ve"] = {text = "這", weight = 1},
    ["vf"] = {text = "真", weight = 1},
    ["vg"] = {text = "正", weight = 1},
    ["vh"] = {text = "長", weight = 1},
    ["vi"] = {text = "只", weight = 1},
    ["vj"] = {text = "戰", weight = 1},
    ["vk"] = {text = "找", weight = 1},
    ["vl"] = {text = "宅", weight = 1},
    ["vo"] = {text = "桌", weight = 1},
    ["vp"] = {text = "準", weight = 1},
    ["vr"] = {text = "專", weight = 2},
    -- ["vr"] = {text = "轉", weight = 1},
    ["vs"] = {text = "中", weight = 1},
    ["vu"] = {text = "主", weight = 1},
    ["vv"] = {text = "追", weight = 1},
    ["vw"] = {text = "抓", weight = 1},
    ["vy"] = {text = "拽", weight = 1},
    ["vz"] = {text = "這", weight = 1},
    ["wa"] = {text = "哇", weight = 1},
    ["wf"] = {text = "問", weight = 1},
    ["wg"] = {text = "翁", weight = 1},
    ["wh"] = {text = "王", weight = 1},
    ["wj"] = {text = "完", weight = 1},
    ["wl"] = {text = "外", weight = 1},
    ["wo"] = {text = "我", weight = 1},
    ["wu"] = {text = "無", weight = 1},
    ["wz"] = {text = "爲", weight = 1},
    ["x;"] = {text = "行", weight = 1},
    ["xc"] = {text = "小", weight = 1},
    ["xd"] = {text = "想", weight = 1},
    ["xi"] = {text = "西", weight = 1},
    ["xm"] = {text = "先", weight = 1},
    ["xn"] = {text = "新", weight = 1},
    ["xp"] = {text = "尋", weight = 1},
    ["xq"] = {text = "秀", weight = 1},
    ["xr"] = {text = "選", weight = 1},
    ["xs"] = {text = "熊", weight = 1},
    ["xt"] = {text = "學", weight = 2},
    -- ["xt"] = {text = "血", weight = 1},
    ["xu"] = {text = "許", weight = 1},
    ["xw"] = {text = "下", weight = 1},
    ["xx"] = {text = "血", weight = 1},
    ["y;"] = {text = "應", weight = 1},
    ["ya"] = {text = "呀", weight = 1},
    ["yb"] = {text = "有", weight = 2},
    -- ["yb"] = {text = "又", weight = 1},
    ["ye"] = {text = "也", weight = 1},
    ["yh"] = {text = "樣", weight = 1},
    ["yi"] = {text = "一", weight = 1},
    ["yj"] = {text = "眼", weight = 1},
    ["yk"] = {text = "要", weight = 1},
    ["yn"] = {text = "因", weight = 1},
    ["yo"] = {text = "喲", weight = 1},
    ["yp"] = {text = "雲", weight = 1},
    ["yr"] = {text = "原", weight = 1},
    ["ys"] = {text = "用", weight = 1},
    ["yt"] = {text = "月", weight = 1},
    ["yu"] = {text = "與", weight = 1},
    ["za"] = {text = "雜", weight = 1},
    ["zb"] = {text = "走", weight = 1},
    ["ze"] = {text = "則", weight = 1},
    ["zf"] = {text = "怎", weight = 1},
    ["zg"] = {text = "增", weight = 1},
    ["zh"] = {text = "髒", weight = 1},
    ["zi"] = {text = "子", weight = 1},
    ["zj"] = {text = "咱", weight = 1},
    ["zk"] = {text = "早", weight = 1},
    ["zl"] = {text = "在", weight = 2},
    ["zo"] = {text = "做", weight = 1},
    ["zp"] = {text = "尊", weight = 1},
    ["zr"] = {text = "鑽", weight = 1},
    ["zs"] = {text = "總", weight = 1},
    ["zu"] = {text = "組", weight = 1},
    ["zv"] = {text = "最", weight = 1},
    ["zz"] = {text = "賊", weight = 1},
    ["rjh"] = {text = "然後", weight = 1},
    ["soy"] = {text = "所以", weight = 1},
    ["lll"] = {text = "來了", weight = 1},
    ["hkl"] = {text = "好了", weight = 1},
    ["uij"] = {text = "時間", weight = 1},
    ["hly"] = {text = "還有", weight = 1},
    ["niu"] = {text = "你是", weight = 1},
    ["wou"] = {text = "我是", weight = 1},
    ["ufm"] = {text = "什麼", weight = 1},
    ["key"] = {text = "可以", weight = 1},
}



-- return {
--     ["b;"] = {text = "冰", weight = 1},
--     ["ba"] = {text = "把", weight = 1},
--     ["bc"] = {text = "表", weight = 1},
--     ["bf"] = {text = "本", weight = 1},
--     ["bg"] = {text = "崩", weight = 1},
--     ["bh"] = {text = "幫", weight = 1},
--     ["bi"] = {text = "比", weight = 1},
--     ["bj"] = {text = "半", weight = 1},
--     ["bk"] = {text = "包", weight = 1},
--     ["bl"] = {text = "白", weight = 1},
--     ["bm"] = {text = "變", weight = 1},
--     ["bn"] = {text = "賓", weight = 1},
--     ["bo"] = {text = "波", weight = 1},
--     ["bu"] = {text = "不", weight = 1},
--     ["bx"] = {text = "別", weight = 1},
--     ["bz"] = {text = "被", weight = 1},
--     ["ca"] = {text = "擦", weight = 1},
--     ["cb"] = {text = "湊", weight = 1},
--     ["ce"] = {text = "測", weight = 1},
--     ["cf"] = {text = "岑", weight = 1},
--     ["cg"] = {text = "層", weight = 1},
--     ["ch"] = {text = "藏", weight = 1},
--     ["ci"] = {text = "次", weight = 1},
--     ["cj"] = {text = "參", weight = 1},
--     ["ck"] = {text = "草", weight = 1},
--     ["cl"] = {text = "才", weight = 1},
--     ["co"] = {text = "錯", weight = 1},
--     ["cp"] = {text = "存", weight = 1},
--     ["cr"] = {text = "竄", weight = 1},
--     ["cs"] = {text = "從", weight = 1},
--     ["cu"] = {text = "粗", weight = 1},
--     ["cv"] = {text = "催", weight = 1},
--     ["d;"] = {text = "定", weight = 1},
--     ["da"] = {text = "大", weight = 1},
--     ["db"] = {text = "都", weight = 1},
--     ["dc"] = {text = "掉", weight = 1},
--     ["dg"] = {text = "等", weight = 1},
--     ["dh"] = {text = "當", weight = 1},
--     ["di"] = {text = "地", weight = 1},
--     ["dj"] = {text = "但", weight = 1},
--     ["dk"] = {text = "到", weight = 1},
--     ["dl"] = {text = "帶", weight = 1},
--     ["dm"] = {text = "點", weight = 1},
--     ["do"] = {text = "多", weight = 1},
--     ["dp"] = {text = "盾", weight = 1},
--     ["dq"] = {text = "丟", weight = 1},
--     ["dr"] = {text = "斷", weight = 1},
--     ["ds"] = {text = "動", weight = 1},
--     ["du"] = {text = "度", weight = 1},
--     ["dv"] = {text = "對", weight = 1},
--     ["dx"] = {text = "爹", weight = 1},
--     ["dz"] = {text = "得", weight = 1},
--     ["fa"] = {text = "發", weight = 1},
--     ["fb"] = {text = "否", weight = 1},
--     ["ff"] = {text = "分", weight = 1},
--     ["fg"] = {text = "風", weight = 1},
--     ["fh"] = {text = "放", weight = 1},
--     ["fj"] = {text = "反", weight = 1},
--     ["fo"] = {text = "佛", weight = 1},
--     ["fu"] = {text = "服", weight = 1},
--     ["fz"] = {text = "飛", weight = 1},
--     ["ga"] = {text = "嘎", weight = 1},
--     ["gb"] = {text = "狗", weight = 1},
--     ["gd"] = {text = "光", weight = 1},
--     ["ge"] = {text = "個", weight = 1},
--     ["gf"] = {text = "跟", weight = 1},
--     ["gg"] = {text = "更", weight = 1},
--     ["gh"] = {text = "剛", weight = 1},
--     ["gj"] = {text = "感", weight = 1},
--     ["gk"] = {text = "高", weight = 1},
--     ["gl"] = {text = "該", weight = 1},
--     ["go"] = {text = "過", weight = 1},
--     ["gp"] = {text = "滾", weight = 1},
--     ["gr"] = {text = "關", weight = 1},
--     ["gs"] = {text = "公", weight = 1},
--     ["gu"] = {text = "古", weight = 1},
--     ["gv"] = {text = "鬼", weight = 1},
--     ["gw"] = {text = "掛", weight = 1},
--     ["gy"] = {text = "怪", weight = 1},
--     ["gz"] = {text = "給", weight = 1},
--     ["ha"] = {text = "哈", weight = 1},
--     ["hb"] = {text = "後", weight = 1},
--     ["hd"] = {text = "黃", weight = 1},
--     ["he"] = {text = "和", weight = 1},
--     ["hf"] = {text = "很", weight = 1},
--     ["hg"] = {text = "哼", weight = 1},
--     ["hh"] = {text = "航", weight = 1},
--     ["hj"] = {text = "漢", weight = 1},
--     ["hk"] = {text = "好", weight = 1},
--     ["hl"] = {text = "還", weight = 1},
--     ["ho"] = {text = "或", weight = 1},
--     ["hp"] = {text = "混", weight = 1},
--     ["hr"] = {text = "換", weight = 1},
--     ["hs"] = {text = "紅", weight = 1},
--     ["hu"] = {text = "乎", weight = 1},
--     ["hv"] = {text = "會", weight = 1},
--     ["hw"] = {text = "話", weight = 1},
--     ["hy"] = {text = "壞", weight = 1},
--     ["hz"] = {text = "黑", weight = 1},
--     ["ia"] = {text = "差", weight = 1},
--     ["ib"] = {text = "抽", weight = 1},
--     ["id"] = {text = "創", weight = 1},
--     ["ie"] = {text = "車", weight = 1},
--     ["if"] = {text = "沉", weight = 1},
--     ["ig"] = {text = "成", weight = 1},
--     ["ih"] = {text = "長", weight = 1},
--     ["ii"] = {text = "喫", weight = 1},
--     ["ij"] = {text = "產", weight = 1},
--     ["ik"] = {text = "超", weight = 1},
--     ["il"] = {text = "拆", weight = 1},
--     ["io"] = {text = "戳", weight = 1},
--     ["ip"] = {text = "純", weight = 1},
--     ["ir"] = {text = "傳", weight = 1},
--     ["is"] = {text = "衝", weight = 1},
--     ["iu"] = {text = "出", weight = 1},
--     ["iv"] = {text = "吹", weight = 1},
--     ["iy"] = {text = "踹", weight = 1},
--     ["j;"] = {text = "經", weight = 1},
--     ["jc"] = {text = "叫", weight = 1},
--     ["jd"] = {text = "將", weight = 1},
--     ["ji"] = {text = "級", weight = 1},
--     ["jm"] = {text = "見", weight = 1},
--     ["jn"] = {text = "進", weight = 1},
--     ["jp"] = {text = "君", weight = 1},
--     ["jq"] = {text = "就", weight = 1},
--     ["jr"] = {text = "卷", weight = 1},
--     ["js"] = {text = "囧", weight = 1},
--     ["jt"] = {text = "絕", weight = 1},
--     ["ju"] = {text = "句", weight = 1},
--     ["jw"] = {text = "家", weight = 1},
--     ["jx"] = {text = "接", weight = 1},
--     ["ka"] = {text = "卡", weight = 1},
--     ["kb"] = {text = "口", weight = 1},
--     ["kd"] = {text = "狂", weight = 1},
--     ["ke"] = {text = "可", weight = 1},
--     ["kf"] = {text = "肯", weight = 1},
--     ["kg"] = {text = "坑", weight = 1},
--     ["kh"] = {text = "抗", weight = 1},
--     ["kj"] = {text = "看", weight = 1},
--     ["kk"] = {text = "靠", weight = 1},
--     ["kl"] = {text = "開", weight = 1},
--     ["ko"] = {text = "擴", weight = 1},
--     ["kp"] = {text = "坤", weight = 1},
--     ["kr"] = {text = "寬", weight = 1},
--     ["ks"] = {text = "空", weight = 1},
--     ["ku"] = {text = "苦", weight = 1},
--     ["kv"] = {text = "虧", weight = 1},
--     ["kw"] = {text = "跨", weight = 1},
--     ["ky"] = {text = "快", weight = 1},
--     ["kz"] = {text = "剋", weight = 1},
--     ["l;"] = {text = "令", weight = 1},
--     ["la"] = {text = "拉", weight = 1},
--     ["lb"] = {text = "樓", weight = 1},
--     ["lc"] = {text = "聊", weight = 1},
--     ["ld"] = {text = "量", weight = 1},
--     ["le"] = {text = "樂", weight = 2},
--     ["le"] = {text = "了", weight = 1},
--     ["lg"] = {text = "冷", weight = 1},
--     ["lh"] = {text = "狼", weight = 1},
--     ["li"] = {text = "裏", weight = 1},
--     ["lj"] = {text = "藍", weight = 1},
--     ["lk"] = {text = "老", weight = 1},
--     ["ll"] = {text = "來", weight = 1},
--     ["lm"] = {text = "連", weight = 1},
--     ["ln"] = {text = "林", weight = 1},
--     ["lo"] = {text = "落", weight = 1},
--     ["lp"] = {text = "論", weight = 1},
--     ["lq"] = {text = "留", weight = 1},
--     ["lr"] = {text = "亂", weight = 1},
--     ["ls"] = {text = "龍", weight = 1},
--     ["lt"] = {text = "略", weight = 1},
--     ["lu"] = {text = "路", weight = 1},
--     ["lw"] = {text = "倆", weight = 1},
--     ["lx"] = {text = "列", weight = 1},
--     ["ly"] = {text = "綠", weight = 1},
--     ["lz"] = {text = "雷", weight = 1},
--     ["m;"] = {text = "明", weight = 1},
--     ["ma"] = {text = "馬", weight = 2},
--     -- ["ma"] = {text = "嗎", weight = 1},
--     ["m"] = {text = "嗎", weight = 1},
--     ["mb"] = {text = "某", weight = 1},
--     ["mc"] = {text = "妙", weight = 1},
--     ["me"] = {text = "麼", weight = 1},
--     ["mf"] = {text = "門", weight = 2},
--     ["mf"] = {text = "們", weight = 1},
--     ["mg"] = {text = "夢", weight = 1},
--     ["mh"] = {text = "忙", weight = 1},
--     ["mi"] = {text = "米", weight = 1},
--     ["mj"] = {text = "滿", weight = 1},
--     ["mk"] = {text = "毛", weight = 1},
--     ["ml"] = {text = "買", weight = 1},
--     ["mm"] = {text = "面", weight = 1},
--     ["mn"] = {text = "民", weight = 1},
--     ["mo"] = {text = "魔", weight = 1},
--     ["mq"] = {text = "謬", weight = 1},
--     ["mu"] = {text = "木", weight = 1},
--     ["mx"] = {text = "滅", weight = 1},
--     ["mz"] = {text = "沒", weight = 1},
--     ["n;"] = {text = "寧", weight = 1},
--     ["na"] = {text = "那", weight = 1},
--     ["nc"] = {text = "鳥", weight = 1},
--     ["nd"] = {text = "娘", weight = 1},
--     ["ne"] = {text = "呢", weight = 1},
--     ["nf"] = {text = "嫩", weight = 1},
--     ["ng"] = {text = "能", weight = 1},
--     ["nh"] = {text = "囊", weight = 1},
--     ["ni"] = {text = "你", weight = 1},
--     ["nj"] = {text = "難", weight = 1},
--     ["nk"] = {text = "鬧", weight = 1},
--     ["nl"] = {text = "奶", weight = 1},
--     ["nm"] = {text = "年", weight = 1},
--     ["nn"] = {text = "您", weight = 1},
--     ["no"] = {text = "諾", weight = 1},
--     ["nq"] = {text = "牛", weight = 1},
--     ["nr"] = {text = "暖", weight = 1},
--     ["ns"] = {text = "弄", weight = 1},
--     ["nt"] = {text = "虐", weight = 1},
--     ["nu"] = {text = "怒", weight = 1},
--     ["nx"] = {text = "捏", weight = 1},
--     ["ny"] = {text = "女", weight = 1},
--     ["nz"] = {text = "內", weight = 1},
--     ["oa"] = {text = "啊", weight = 1},
--     ["ob"] = {text = "歐", weight = 1},
--     ["oe"] = {text = "呃", weight = 1},
--     ["of"] = {text = "嗯", weight = 1},
--     ["og"] = {text = "嗯", weight = 1},
--     ["oh"] = {text = "昂", weight = 1},
--     ["oj"] = {text = "安", weight = 1},
--     ["ok"] = {text = "奧", weight = 1},
--     ["ol"] = {text = "哎", weight = 1},
--     ["oo"] = {text = "哦", weight = 1},
--     ["or"] = {text = "而", weight = 1},
--     ["oz"] = {text = "誒", weight = 1},
--     ["p;"] = {text = "平", weight = 1},
--     ["pa"] = {text = "爬", weight = 1},
--     ["pb"] = {text = "剖", weight = 1},
--     ["pc"] = {text = "票", weight = 1},
--     ["pf"] = {text = "噴", weight = 1},
--     ["pg"] = {text = "朋", weight = 1},
--     ["ph"] = {text = "旁", weight = 1},
--     ["pi"] = {text = "皮", weight = 1},
--     ["pj"] = {text = "盤", weight = 1},
--     ["pk"] = {text = "跑", weight = 1},
--     ["pl"] = {text = "排", weight = 1},
--     ["pm"] = {text = "片", weight = 1},
--     ["pn"] = {text = "品", weight = 1},
--     ["po"] = {text = "破", weight = 1},
--     ["pu"] = {text = "普", weight = 1},
--     ["px"] = {text = "撇", weight = 1},
--     ["pz"] = {text = "陪", weight = 1},
--     ["q;"] = {text = "請", weight = 1},
--     ["qc"] = {text = "巧", weight = 1},
--     ["qd"] = {text = "強", weight = 1},
--     ["qi"] = {text = "其", weight = 1},
--     ["qm"] = {text = "前", weight = 1},
--     ["qn"] = {text = "親", weight = 1},
--     ["qp"] = {text = "羣", weight = 1},
--     ["qq"] = {text = "求", weight = 1},
--     ["qr"] = {text = "全", weight = 1},
--     ["qs"] = {text = "窮", weight = 1},
--     ["qt"] = {text = "卻", weight = 1},
--     ["qu"] = {text = "去", weight = 1},
--     ["qw"] = {text = "恰", weight = 1},
--     ["qx"] = {text = "且", weight = 1},
--     ["rb"] = {text = "肉", weight = 1},
--     ["re"] = {text = "熱", weight = 1},
--     ["rf"] = {text = "人", weight = 1},
--     ["rg"] = {text = "仍", weight = 1},
--     ["rh"] = {text = "讓", weight = 1},
--     ["ri"] = {text = "日", weight = 1},
--     ["rj"] = {text = "然", weight = 1},
--     ["rk"] = {text = "繞", weight = 1},
--     ["ro"] = {text = "若", weight = 1},
--     ["rp"] = {text = "潤", weight = 1},
--     ["rr"] = {text = "軟", weight = 1},
--     ["rs"] = {text = "容", weight = 1},
--     ["ru"] = {text = "如", weight = 2},
--     ["ru"] = {text = "入", weight = 1},
--     ["rv"] = {text = "瑞", weight = 1},
--     ["sa"] = {text = "薩", weight = 1},
--     ["sb"] = {text = "搜", weight = 1},
--     ["se"] = {text = "色", weight = 1},
--     ["sf"] = {text = "森", weight = 1},
--     ["sg"] = {text = "僧", weight = 1},
--     ["sh"] = {text = "喪", weight = 1},
--     ["si"] = {text = "死", weight = 1},
--     ["sj"] = {text = "三", weight = 1},
--     ["sk"] = {text = "掃", weight = 1},
--     ["sl"] = {text = "賽", weight = 1},
--     ["so"] = {text = "所", weight = 1},
--     ["sp"] = {text = "孫", weight = 1},
--     ["sr"] = {text = "算", weight = 1},
--     ["ss"] = {text = "送", weight = 1},
--     ["su"] = {text = "訴", weight = 1},
--     ["sv"] = {text = "雖", weight = 1},
--     ["sz"] = {text = "塞", weight = 0},
--     ["t;"] = {text = "聽", weight = 1},
--     ["ta"] = {text = "他", weight = 1},
--     ["tb"] = {text = "頭", weight = 1},
--     ["tc"] = {text = "條", weight = 1},
--     ["te"] = {text = "特", weight = 1},
--     ["tg"] = {text = "疼", weight = 1},
--     ["th"] = {text = "唐", weight = 1},
--     ["ti"] = {text = "題", weight = 1},
--     ["tj"] = {text = "談", weight = 1},
--     ["tk"] = {text = "逃", weight = 1},
--     ["tl"] = {text = "太", weight = 1},
--     ["tm"] = {text = "天", weight = 1},
--     ["to"] = {text = "拖", weight = 1},
--     ["tp"] = {text = "屯", weight = 1},
--     ["tr"] = {text = "團", weight = 1},
--     ["ts"] = {text = "同", weight = 1},
--     ["tu"] = {text = "土", weight = 1},
--     ["tv"] = {text = "推", weight = 2},
--     ["tv"] = {text = "退", weight = 1},
--     ["tx"] = {text = "鐵", weight = 1},
--     ["ua"] = {text = "啥", weight = 1},
--     ["ub"] = {text = "手", weight = 1},
--     ["ud"] = {text = "爽", weight = 1},
--     ["ue"] = {text = "射", weight = 1},
--     ["uf"] = {text = "神", weight = 1},
--     ["ug"] = {text = "生", weight = 1},
--     ["uh"] = {text = "上", weight = 1},
--     ["u"] = {text = "是", weight = 1},
--     ["ui"] = {text = "時", weight = 2},
--     ["uj"] = {text = "山", weight = 1},
--     ["uk"] = {text = "少", weight = 1},
--     ["ul"] = {text = "曬", weight = 1},
--     ["uo"] = {text = "說", weight = 1},
--     ["up"] = {text = "順", weight = 1},
--     ["ur"] = {text = "涮", weight = 1},
--     ["uu"] = {text = "書", weight = 2},
--     ["uu"] = {text = "數", weight = 1},
--     ["uv"] = {text = "睡", weight = 3},
--     ["uv"] = {text = "水", weight = 2},
--     ["uv"] = {text = "誰", weight = 1},
--     ["uw"] = {text = "刷", weight = 1},
--     ["uy"] = {text = "帥", weight = 1},
--     ["uz"] = {text = "誰", weight = 1},
--     ["va"] = {text = "炸", weight = 1},
--     ["vb"] = {text = "舟", weight = 1},
--     ["vd"] = {text = "裝", weight = 1},
--     ["ve"] = {text = "這", weight = 1},
--     ["vf"] = {text = "真", weight = 1},
--     ["vg"] = {text = "正", weight = 1},
--     ["vh"] = {text = "長", weight = 1},
--     ["vi"] = {text = "只", weight = 1},
--     ["vj"] = {text = "戰", weight = 1},
--     ["vk"] = {text = "找", weight = 1},
--     ["vl"] = {text = "宅", weight = 1},
--     ["vo"] = {text = "桌", weight = 1},
--     ["vp"] = {text = "準", weight = 1},
--     ["vr"] = {text = "專", weight = 2},
--     ["vr"] = {text = "轉", weight = 1},
--     ["vs"] = {text = "中", weight = 1},
--     ["vu"] = {text = "主", weight = 1},
--     ["vv"] = {text = "追", weight = 1},
--     ["vw"] = {text = "抓", weight = 1},
--     ["vy"] = {text = "拽", weight = 1},
--     ["vz"] = {text = "這", weight = 1},
--     ["wa"] = {text = "哇", weight = 1},
--     ["wf"] = {text = "問", weight = 1},
--     ["wg"] = {text = "翁", weight = 1},
--     ["wh"] = {text = "王", weight = 1},
--     ["wj"] = {text = "完", weight = 1},
--     ["wl"] = {text = "外", weight = 1},
--     ["wo"] = {text = "我", weight = 1},
--     ["wu"] = {text = "無", weight = 1},
--     ["wz"] = {text = "爲", weight = 1},
--     ["x;"] = {text = "行", weight = 1},
--     ["xc"] = {text = "小", weight = 1},
--     ["xd"] = {text = "想", weight = 1},
--     ["xi"] = {text = "西", weight = 1},
--     ["xm"] = {text = "先", weight = 1},
--     ["xn"] = {text = "新", weight = 1},
--     ["xp"] = {text = "尋", weight = 1},
--     ["xq"] = {text = "秀", weight = 1},
--     ["xr"] = {text = "選", weight = 1},
--     ["xs"] = {text = "熊", weight = 1},
--     ["xt"] = {text = "學", weight = 2},
--     ["xt"] = {text = "血", weight = 1},
--     ["xu"] = {text = "許", weight = 1},
--     ["xw"] = {text = "下", weight = 1},
--     ["xx"] = {text = "血", weight = 1},
--     ["y;"] = {text = "應", weight = 1},
--     ["ya"] = {text = "呀", weight = 1},
--     ["yb"] = {text = "有", weight = 2},
--     ["yb"] = {text = "又", weight = 1},
--     ["ye"] = {text = "也", weight = 1},
--     ["yh"] = {text = "樣", weight = 1},
--     ["yi"] = {text = "一", weight = 1},
--     ["yj"] = {text = "眼", weight = 1},
--     ["yk"] = {text = "要", weight = 1},
--     ["yn"] = {text = "因", weight = 1},
--     ["yo"] = {text = "喲", weight = 1},
--     ["yp"] = {text = "雲", weight = 1},
--     ["yr"] = {text = "原", weight = 1},
--     ["ys"] = {text = "用", weight = 1},
--     ["yt"] = {text = "月", weight = 1},
--     ["yu"] = {text = "與", weight = 1},
--     ["za"] = {text = "雜", weight = 1},
--     ["zb"] = {text = "走", weight = 1},
--     ["ze"] = {text = "則", weight = 1},
--     ["zf"] = {text = "怎", weight = 1},
--     ["zg"] = {text = "增", weight = 1},
--     ["zh"] = {text = "髒", weight = 1},
--     ["zi"] = {text = "子", weight = 1},
--     ["zj"] = {text = "咱", weight = 1},
--     ["zk"] = {text = "早", weight = 1},
--     ["zl"] = {text = "在", weight = 2},
--     ["zo"] = {text = "做", weight = 1},
--     ["zp"] = {text = "尊", weight = 1},
--     ["zr"] = {text = "鑽", weight = 1},
--     ["zs"] = {text = "總", weight = 1},
--     ["zu"] = {text = "組", weight = 1},
--     ["zv"] = {text = "最", weight = 1},
--     ["zz"] = {text = "賊", weight = 1}
-- }